stages:
  - build
  - test

before_script:
    - rm -f titanium.lua
    - rm -f titanium.min.lua
    - apt-get update && apt-get -y install lua5.1 luarocks
    - luarocks install luafilesystem

.job_template: &test_definition
  before_script:
    - apt-get update && apt-get -y install lua5.1 luarocks cmake
    - luarocks install luafilesystem
    - luarocks install penlight
    - luarocks install luv
    - luarocks install luaposix
    - git clone https://github.com/CoderPuppy/cc-emu emu --branch for-ci
    - cd emu
    - git clone https://github.com/CoderPuppy/ComputercraftLua cc --branch ci
    - cd /

build:
  stage: build
  script:
    - echo "Running development build. Not building minified"
    - lua5.1 ./bin/construct.lua --source src --output titanium.lua
  artifacts:
    paths:
      - titanium.lua
  except:
    - master

build-release:
  stage: build
  script:
    - echo "Running release build. Building minified"
    - lua5.1 ./bin/construct.lua --source src --output titanium.lua
    - lua5.1 ./bin/construct.lua --source src --output titanium.min.lua --minify
  artifacts:
    paths:
      - titanium.lua
      - titanium.min.lua
  only:
    - master

test:
  <<: *test_definition
  stage: test
  script:
    - echo "Testing development build"
    - lua5.1 /emu/cli.lua /bin/ci run_test.lua /build/titanium.lua tml
  except:
    - master

test-release:
  <<: *test_definition
  stage: test
  script:
    - echo "Testing release builds"
    - lua5.1 /emu/cli.lua /bin/ci run_test.lua /build/titanium.lua tml
    - lua5.1 /emu/cli.lua /bin/ci run_test.lua /build/titanium.min.lua tml
  only:
    - master

# Cache files outside git index
cache:
  untracked: true
